---
argument_specs:
  main:
    short_description: Manage the Technitium DNS floating address
    options:
      technitium_keepalived_enabled:
        type: bool
        default: false
      technitium_keepalived_interface:
        type: str
        default: eth0
      technitium_keepalived_virtual_ipv4_address:
        type: str
        required: false
      technitium_keepalived_peer_ipv4_address:
        type: str
        required: false
      technitium_keepalived_cluster_domain:
        type: str
        required: false
      technitium_keepalived_virtual_router_id:
        type: int
        default: 53
      technitium_keepalived_priority:
        type: int
        default: 100
      technitium_keepalived_state:
        type: str
        choices:
          - MASTER
          - BACKUP
        default: BACKUP
